name: Run Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run Cypress Tests (Headless)
      run: |
        node cli.js --parallel --threads 4 --browser chrome --headless --resolutions 1920x1080 1440x900 1366x768 800x600 768x1024 375x667 --html --xml --spec "cypress/e2e/**/*.cy.js"
        node cli.js --parallel --threads 4 --browser firefox --headless --resolutions 1920x1080 1440x900 1366x768 800x600 768x1024 375x667 --html --xml --spec "cypress/e2e/**/*.cy.js"
        node cli.js --parallel --threads 4 --browser electron --headless --resolutions 1920x1080 1440x900 1366x768 800x600 768x1024 375x667 --html --xml --spec "cypress/e2e/**/*.cy.js"
        node cli.js --parallel --threads 4 --browser edge --headless --resolutions 1920x1080 1440x900 1366x768 800x600 768x1024 375x667 --html --xml --spec "cypress/e2e/**/*.cy.js"
        node cli.js --parallel --threads 4 --browser webkit --headless --resolutions 1920x1080 1440x900 1366x768 800x600 768x1024 375x667 --html --xml --spec "cypress/e2e/**/*.cy.js"

    - name: Deploy Cypress Reports to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: cypress/results/