name: Run Cypress Tests and Deploy Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chrome, firefox]  # Add more browsers as needed (e.g., electron, edge)
        resolution: ['1920x1080', '1366x768', '375x667']  # Add more resolutions as needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb libxi6  # Removed libgconf-2-4 due to issues
          npm install

      - name: Start Xvfb with Resolution ${{ matrix.resolution }}
        run: |
          export DISPLAY=:99
          nohup Xvfb :99 -screen 0 ${matrix.resolution}x24 &  # Set resolution dynamically
          # Wait for Xvfb to initialize
          sleep 5
          # Check if Xvfb is running
          ps aux | grep Xvfb || exit 1

      - name: Run Cypress Tests (Headless)
        run: |
          export DISPLAY=:99
          # Run Cypress tests for the current browser and resolution
          npx cypress run --headless --browser ${{ matrix.browser }} --spec "cypress/e2e/**/*.cy.js" --config viewportWidth=${{ matrix.resolution.split('x')[0] }},viewportHeight=${{ matrix.resolution.split('x')[1] }}

      - name: Generate HTML Report
        run: |
          npx mochawesome-merge cypress/results/**/*.json > cypress/results/report.json
          npx mochawesome-report-generator cypress/results/report.json -o cypress/results

      - name: Deploy Cypress Reports to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: cypress/results/
          target_branch: gh-pages  # The branch where the report will be deployed
          commit_message: "Deploy Cypress test report to GitHub Pages"
          user_name: 'GitHub Actions'
          user_email: 'github-actions@users.noreply.github.com'