name: Run Cypress Tests Across Browsers and Deploy Report

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chrome]  # , firefox, electron - Add 'edge' if supported in your setup
        resolution: ['1920x1080', '1366x768', '375x667']  # Add more resolutions as needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb libgconf-2-4 libxi6
          npm install

      - name: Start Xvfb
        run: |
          export DISPLAY=:99
          nohup Xvfb :99 -screen 0 1280x1024x24 &

      - name: Run Cypress tests on ${{ matrix.browser }} with resolution ${{ matrix.resolution }}
        env:
          DISPLAY: ":99"
        run: |
          npx cypress run --headless --browser ${{ matrix.browser }} --spec "cypress/e2e/**/*.cy.js" --config viewportWidth=${{ matrix.resolution.split('x')[0] }},viewportHeight=${{ matrix.resolution.split('x')[1] }} --reporter mochawesome --reporter-options reportDir=cypress/results/${{ matrix.browser }}-${{ matrix.resolution }}

      - name: Generate HTML Report
        run: |
          npx mochawesome-merge cypress/results/**/*.json > cypress/results/report.json
          npx mochawesome-report-generator cypress/results/report.json -o cypress/results

      - name: Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          folder: cypress/results  # Specify the folder containing the HTML report
          target_branch: gh-pages  # This is the branch where the report will be deployed
          commit_message: "Deploy Cypress test report to GitHub Pages"
          user_name: 'GitHub Actions'
          user_email: 'github-actions@users.noreply.github.com'