
name: Run Cypress Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb libgconf-2-4 libxi6
        npm install
    - name: Start Xvfb
      run: |
        export DISPLAY=:99
        nohup Xvfb :99 -screen 0 1280x1024x24 &
    - name: Run Cypress Tests (Headless)
      run: |
        export DISPLAY=:99
        npx cypress run --parallel --headless --browser chrome --spec "cypress/e2e/**/*.cy.js"
        npx cypress run --parallel --headless --browser firefox --spec "cypress/e2e/**/*.cy.js"
       # npx cypress run --parallel --headless --browser electron --spec "cypress/e2e/**/*.cy.js"
        #npx cypress run --parallel --headless --browser edge --spec "cypress/e2e/**/*.cy.js"
        #npx cypress run --parallel --headless --browser webkit --spec "cypress/e2e/**/*.cy.js"
    - name: Deploy Cypress Reports to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: cypress/results/
