name: Run Cypress Tests and Deploy Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chrome]  # Add more browsers like firefox, electron
        resolution: ['1920x1080', '1366x768', '375x667']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb libxi6
          npm install

      - name: Start Xvfb
        run: |
          export DISPLAY=:99
          nohup Xvfb :99 -screen 0 1920x1080x24 &
          sleep 3

      - name: Run Cypress Tests - ${{ matrix.browser }} @ ${{ matrix.resolution }}
        env:
          DISPLAY: ":99"
        run: |
          WIDTH=${{ matrix.resolution.split('x')[0] }}
          HEIGHT=${{ matrix.resolution.split('x')[1] }}
          npx cypress run \
            --headless \
            --browser ${{ matrix.browser }} \
            --spec "cypress/e2e/**/*.cy.js" \
            --config viewportWidth=$WIDTH,viewportHeight=$HEIGHT \
            --reporter mochawesome \
            --reporter-options reportDir=cypress/results/${{ matrix.browser }}-${{ matrix.resolution }},overwrite=false,html=false,json=true

      - name: Merge Mochawesome Reports
        if: always()
        run: |
          npx mochawesome-merge cypress/results/**/mochawesome*.json > cypress/results/merged-report.json
          npx mochawesome-report-generator cypress/results/merged-report.json -o cypress/results/html

      - name: Deploy Cypress Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: cypress/results/html
          target_branch: gh-pages
          commit_message: "Deploy Cypress test report"
          user_name: 'GitHub Actions'
          user_email: 'github-actions@users.noreply.github.com'