name: Run Cypress Tests and Deploy Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb libxi6  # Avoid libgconf-2-4 for now
          npm install

      - name: Verify Xvfb Installation
        run: |
          echo "Checking Xvfb installation..."
          which Xvfb
          Xvfb --version

      - name: Start Xvfb with resolution 1920x1080
        run: |
          export DISPLAY=:99
          echo "Starting Xvfb with resolution 1920x1080"
          nohup Xvfb :99 -screen 0 1920x1080x24 &
          # Give Xvfb time to initialize
          sleep 5
          # Check if Xvfb is running
          ps aux | grep Xvfb || (echo "Xvfb failed to start!" && exit 1)  # Fail early if Xvfb fails

      - name: Run Cypress Tests (Headless)
        run: |
          export DISPLAY=:99
          echo "Running Cypress tests"
          npx cypress run --headless --browser chrome --spec "cypress/e2e/**/*.cy.js"

      - name: Generate HTML Report
        run: |
          echo "Generating Mochawesome report"
          npx mochawesome-merge cypress/results/**/*.json > cypress/results/report.json
          npx mochawesome-report-generator cypress/results/report.json -o cypress/results

      - name: Deploy Cypress Reports to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: cypress/results/
          target_branch: gh-pages  # The branch where the report will be deployed
          commit_message: "Deploy Cypress test report to GitHub Pages"
          user_name: 'GitHub Actions'
          user_email: 'github-actions@users.noreply.github.com'