name: Run Cypress Tests and Deploy Reports

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chrome]
        resolution: ['1920x1080', '1366x768', '375x667']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb libxi6
          npm install

      - name: Start Xvfb
        run: |
          export DISPLAY=:99
          nohup Xvfb :99 -screen 0 1920x1080x24 &
          sleep 3

      - name: Run Cypress Tests - ${{ matrix.browser }} @ ${{ matrix.resolution }}
        env:
          DISPLAY: ":99"
        shell: bash
        run: |
          RES="${{ matrix.resolution }}"
          WIDTH="${RES%x*}"
          HEIGHT="${RES#*x}"
          REPORT_DIR="cypress/results/${{ matrix.browser }}-${RES}"

          echo "Running tests at ${WIDTH}x${HEIGHT} on ${{ matrix.browser }}"
          
          npx cypress run \
            --headless \
            --browser ${{ matrix.browser }} \
            --spec "cypress/e2e/**/*.cy.js" \
            --config viewportWidth=$WIDTH,viewportHeight=$HEIGHT \
            --reporter mochawesome \
            --reporter-options reportDir=${REPORT_DIR},overwrite=false,html=false,json=true

          echo "Generating HTML report for $REPORT_DIR"
          npx mochawesome-merge ${REPORT_DIR}/mochawesome*.json > ${REPORT_DIR}/merged.json
          npx mochawesome-report-generator ${REPORT_DIR}/merged.json -o ${REPORT_DIR}/html

      - name: Create index.html for navigation
        if: always()
        run: |
          mkdir -p cypress/results/html
          echo "<html><body><h1>Cypress Test Reports</h1><ul>" > cypress/results/html/index.html
          for dir in cypress/results/*-*; do
            COMBO=$(basename "$dir")
            echo "<li><a href=\"../${COMBO}/html/index.html\">${COMBO}</a></li>" >> cypress/results/html/index.html
          done
          echo "</ul></body></html>" >> cypress/results/html/index.html

      - name: Publish test reports
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: cypress/results
          commit_message: "Deploy separate Cypress test reports"
          user_name: 'GitHub Actions'
          user_email: 'github-actions@users.noreply.github.com'
          force: true